#Project Title: Mathematical & Statistical Analysis for Data Science





#Task 1 - Linear Algebra Implementation

In [1]:
import numpy as np

vector_a = np.array([2, 4, 6])
vector_b = np.array([1, 3, 5])

matrix_a = np.array([
    [2, 1, 3],
    [1, 0, 2],
    [4, 1, 1]
])

matrix_b = np.array([
    [1, 2, 0],
    [3, 1, 4],
    [2, 5, 1]
])

print("Vector A:", vector_a)
print("Vector B:", vector_b)

# Addition
vector_add = vector_a + vector_b
print("\nVector Addition:", vector_add)

# Subtraction
vector_sub = vector_a - vector_b
print("Vector Subtraction:", vector_sub)

# Dot Product
dot_product = np.dot(vector_a, vector_b)
print("Dot Product:", dot_product)

print("\nMatrix A:\n", matrix_a)
print("Matrix B:\n", matrix_b)

# Matrix Addition
matrix_add = matrix_a + matrix_b
print("\nMatrix Addition:\n", matrix_add)

# Matrix Multiplication
matrix_mul = np.dot(matrix_a, matrix_b)
print("\nMatrix Multiplication:\n", matrix_mul)

determinant = np.linalg.det(matrix_a)
print("\nDeterminant of Matrix A:", determinant)

# Inverse (only if determinant ≠ 0)
if determinant != 0:
    inverse = np.linalg.inv(matrix_a)
    print("\nInverse of Matrix A:\n", inverse)
else:
    print("\nMatrix A is singular; inverse does not exist.")

eigenvalues, eigenvectors = np.linalg.eig(matrix_a)

print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

Vector A: [2 4 6]
Vector B: [1 3 5]

Vector Addition: [ 3  7 11]
Vector Subtraction: [1 1 1]
Dot Product: 44

Matrix A:
 [[2 1 3]
 [1 0 2]
 [4 1 1]]
Matrix B:
 [[1 2 0]
 [3 1 4]
 [2 5 1]]

Matrix Addition:
 [[3 3 3]
 [4 1 6]
 [6 6 2]]

Matrix Multiplication:
 [[11 20  7]
 [ 5 12  2]
 [ 9 14  5]]

Determinant of Matrix A: 6.0

Inverse of Matrix A:
 [[-0.33333333  0.33333333  0.33333333]
 [ 1.16666667 -1.66666667 -0.16666667]
 [ 0.16666667  0.33333333 -0.16666667]]

Eigenvalues:
 [ 5.54138127 -2.         -0.54138127]

Eigenvectors:
 [[-0.66037269 -0.42163702  0.17485589]
 [-0.3575134  -0.52704628 -0.96894315]
 [-0.66037269  0.73786479  0.17485589]]


#Task 2 – Probability Concepts

In [2]:
import numpy as np
from scipy.stats import binom

def main():
    sales_success = [0.65, 0.35]

    prob_success = sales_success[0]
    prob_failure = sales_success[1]

    print("1. Probability of Successful Sales")
    print("P(Success):", prob_success)
    print("P(Failure):", prob_failure)

    customer_segments = ["Premium", "Regular"]
    segment_purchase_probability = {
        "Premium": 0.80,
        "Regular": 0.50
    }

    print("\n2. Conditional Probability")
    for segment in customer_segments:
        print(f"P(Purchase | {segment}) = {segment_purchase_probability[segment]}")

    P_A = 0.40              # Premium customer
    P_B = 0.62              # Purchase
    P_B_given_A = 0.80      # Purchase given Premium

    P_A_given_B = (P_B_given_A * P_A) / P_B

    print("\n3. Bayes’ Theorem")
    print("P(Premium | Purchase):", round(P_A_given_B, 4))

    n_trials = 20
    success_prob = 0.65

    samples = np.random.binomial(n_trials, success_prob, size=10)

    print("\n4. Binomial Distribution (20 Trials)")
    print("Sample outcomes:", samples)

    k = 12
    prob_k = binom.pmf(k, n_trials, success_prob)
    print(f"Probability of exactly {k} successes:", round(prob_k, 4))

    normal_mean = 50
    normal_std = 10

    normal_data = np.random.normal(normal_mean, normal_std, 10)

    print("\n5. Normal Distribution Sample")
    print(normal_data)

    uniform_low = 0
    uniform_high = 1

    uniform_data = np.random.uniform(uniform_low, uniform_high, 10)

    print("\n6. Uniform Distribution Sample")
    print(uniform_data)

if __name__ == "__main__":
    main()

1. Probability of Successful Sales
P(Success): 0.65
P(Failure): 0.35

2. Conditional Probability
P(Purchase | Premium) = 0.8
P(Purchase | Regular) = 0.5

3. Bayes’ Theorem
P(Premium | Purchase): 0.5161

4. Binomial Distribution (20 Trials)
Sample outcomes: [15 15 16 16 15 11 11 11 14 14]
Probability of exactly 12 successes: 0.1614

5. Normal Distribution Sample
[45.62678252 59.78255792 70.30683592 57.09296459 63.43423297 53.40333652
 51.24517087 49.65179803 48.73576618 57.47244615]

6. Uniform Distribution Sample
[0.50117474 0.94724963 0.21231054 0.74666389 0.53702823 0.52540756
 0.88661901 0.13656064 0.34079745 0.9490756 ]


#Task 3 – Descriptive Statistics

In [3]:
import numpy as np
import pandas as pd
from scipy.stats import skew, kurtosis
import statistics

def main():

    sales_data = [120, 135, 150, 145, 160, 155, 170, 165, 180, 175,
                  190, 200, 210, 195, 185, 175, 165, 155, 145, 135]

    data = np.array(sales_data)

    mean_val = np.mean(data)
    median_val = np.median(data)
    mode_val = statistics.mode(data)

    print("1. Central Tendency")
    print("Mean:", mean_val)
    print("Median:", median_val)
    print("Mode:", mode_val)

    data_range = np.max(data) - np.min(data)
    variance_val = np.var(data)
    std_dev_val = np.std(data)

    print("\n2. Dispersion Measures")
    print("Range:", data_range)
    print("Variance:", variance_val)
    print("Standard Deviation:", std_dev_val)

    skewness_val = skew(data)
    kurtosis_val = kurtosis(data)

    print("\n3. Shape of Distribution")
    print("Skewness:", skewness_val)
    print("Kurtosis:", kurtosis_val)

    print("\n4. Interpretation")

    if skewness_val > 0:
        print("The dataset is positively skewed (right-skewed).")
    elif skewness_val < 0:
        print("The dataset is negatively skewed (left-skewed).")
    else:
        print("The dataset is symmetric.")

    if abs(skewness_val) < 0.5:
        print("Skewness is close to zero → approximately symmetric distribution.")

    if kurtosis_val > 0:
        print("Leptokurtic distribution (more peaked than normal).")
    elif kurtosis_val < 0:
        print("Platykurtic distribution (flatter than normal).")
    else:
        print("Mesokurtic distribution (normal-like).")

if __name__ == "__main__":
    main()

1. Central Tendency
Mean: 165.5
Median: 165.0
Mode: 135

2. Dispersion Measures
Range: 90
Variance: 534.75
Standard Deviation: 23.124662159694356

3. Shape of Distribution
Skewness: 0.030143346252736614
Kurtosis: -0.7069943289224954

4. Interpretation
The dataset is positively skewed (right-skewed).
Skewness is close to zero → approximately symmetric distribution.
Platykurtic distribution (flatter than normal).
